version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=leonel 
    #environment:
     # - POSTGRES_HOST_AUTH_METHOD=trust
        #- POSTGRES_PASSWORD: hamilton
       # - POSTGRES_DB: f1
        #- POSTGRES_USER: leonel
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      