version: "3"

services:
  postgres: 
    image: postgres:12.4
    container_name: pg
    restart: always
    volumes:
      - ./vol/pg_data:/var/lib/postgresql/data:rw
    ports:
        - 5432:5432
    environment:
      - POSTGRES_DB=f1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=leonel
      - POSTGRES_HOST_AUTH_METHOD=md5
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "su", "-", "postgres", "pg_isready", "-d", "db_prod"]
      interval: 1s
      timeout: 6s
      retries: 10
      start_period: 1s
  python_app:
    container_name: python_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - 8080:8080
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=leonel
      - PG_HOST=pg
      - PG_PORT=5432
      - PG_DATABASE=f1
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - db
    tty: true

networks:
    db:
       driver: bridge
      
